### ISSUE TITLE
Data could not be found as per directed

### ISSUE THREAD

**Issue by Sudar278** [yifanlu0227/ChatSim#12]
Downloaded the data and stored in the mentioned location

![image](https://github.com/yifanlu0227/ChatSim/assets/119469584/5d2e9abf-ad9c-4aed-bd5f-d0d640630f5b)

The following command is not creating the waymo_multi_view folder and seems the script is not running

![image](https://github.com/yifanlu0227/ChatSim/assets/119469584/cbff5ee8-3ff6-4293-b3c5-64d5b719b63c)

**Comment by yifanlu0227** [comment]
Oh, this is because the file names downloaded from the gcloud console and gsutil are different.

If you download the files one by one from the gcloud console, they will have prefixes like "individual_files_training". In the latest commit, we make `process_waymo_script.py` available to these files. Please run

```
git fetch origin
git merge origin/main
```

to merge the latest commit.
