### ISSUE TITLE
mc_to_light代码运行不起来

### ISSUE THREAD

**Issue by StarsTesla** [yifanlu0227/ChatSim#36]
我按照你的那个readme，install了skydomexxx包，然后运行train第一阶段，但是有很多包的导入问题，反正很多小错误，最典的是
```python
from mc_to_sky.data_utils.holicity_sdr_centered_dataset import HoliCitySDRCenteredDataset
```
根本没有这个文件。。。。。。。

**Comment by StarsTesla** [comment]
unet也找不到，
    from ..model.sub_module.unet import UNet
ModuleNotFoundError: No module named 'mc_to_sky.model.sub_module.unet'

**Comment by StarsTesla** [comment]
如果修复了跑通了踢我一下

**Comment by yifanlu0227** [comment]
收到，这些是我们做ablation study时候的code，release的时候删除了相关代码文件但是没有改import。我们这两天会清理一下，确保可以运行，感谢反馈！

**Comment by yifanlu0227** [comment]
We fixed the bugs in [this commit](https://github.com/yifanlu0227/ChatSim/commit/912e1a646b3c8a600b2b9d5d74e36300dab09c2b), and have tested all the commands in the README. 


Note that we removed a lot of unnecessary dependency in McLight's `requirements.txt` and used the `pytorch_lightning 2.0.3` following the main `requirements.txt`.  Also run`python setup.py develop` in `chatsim/foreground/mclight/skydome_lighting` again since we correct the package name. Ensuring these allows you run the code behind smoothly.

We listen to any feedback from you.

**Comment by StarsTesla** [comment]
![image](https://github.com/yifanlu0227/ChatSim/assets/45264423/3f95baea-83ba-499f-917f-f6c96f46ce7d)
@yifanlu0227 这是我全程follow跑下来的，1027（019）waymo场景，天空光的方向是对的，但是这个阴影blender好像渲染不出那么强烈的

**Comment by yifanlu0227** [comment]
我们用Shadow Catcher 单独提取出地面的阴影，并且和背景地面的颜色相乘，相当于用background的颜色进一步调色。所以你在blender界面看到的阴影颜色会和最终合成的结果不一样。这些操作步骤你可以在compositing的节点图里看到。

另一方面，阴影可能不够强烈的原因在于HDRI的峰值亮度估计的还是不准。

**Comment by StarsTesla** [comment]
damn！
